### ISSUE TITLE
pprof server doesn't seem to be honored

### ISSUE THREAD

**Issue by schmidtw** [Comcast/tr1d1um#434]
The following code doesn't appear to be honored & pprof doesn't get started.

```yaml
servers:
  pprof:
    address: 127.0.0.1:9999
    readTimeout: "15s"
    idleTimeout: "15s"
```

I see the server should be created, based on the code below, but I don't see how it's being routed to pprof and it's not working.
https://github.com/xmidt-org/tr1d1um/blob/06c3c97c274e87ae30feb57530f96185442d86bf/routes.go#L184
